apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: client2-prometheus
  namespace: client2
  annotations:
    kubernetes.io/ingress.class: kong-client2
  labels:
    global: "true"
plugin: prometheus
config:
  status_code_metrics: true
  bandwidth_metrics: true
  upstream_health_metrics: true
  latency_metrics: true
  per_consumer: true
