# See => https://medium.com/@sayyedjilani8/kube-events-using-websockets-a-demo-application-833df14d7f89
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-kube-connector
  namespace: client1
spec:
  selector:
    matchLabels:
      app: websocket-kube-connector
  template:
    metadata:
      labels:
        app: websocket-kube-connector
    spec:
      serviceAccount: kube-connector
      containers:
        - name: kube-connector
          image: jilani1/kube-connector-go:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-kube-connector
  namespace: client1
  annotations:
    konghq.com/read-timeout: "120000"
    konghq.com/write-timeout: "120000"
spec:
  selector:
    app: websocket-kube-connector
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-connector
  namespace: client1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-connector-cluster-role
rules:
  - apiGroups: ["*"]
    resources:
      [
        "namespaces",
        "pods",
        "services",
        "nodes",
        "endpoints",
        "secrets",
        "configmaps",
        "persistentvolumeclaims",
        "persistentvolumes",
        "events",
        "ingresses",
        "componentstatuses",
        "deployments",
        "replicasets",
        "daemonsets",
        "statefulsets",
      ]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-connector-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-connector-cluster-role
subjects:
  - kind: ServiceAccount
    name: kube-connector
    namespace: client1
