apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: client1-request-caching
  namespace: client1
  annotations:
    kubernetes.io/ingress.class: kong-client1
config:
    response_code:
    - 200
    request_method:
    - GET
    content_type:
    - application/json
    cache_ttl: 300
    strategy: memory
plugin: proxy-cache