apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: client1-oidc
  namespace: client1
  annotations:
    kubernetes.io/ingress.class: kong-client1
config:
  issuer: https://sso.apim.eu:8443/auth/realms/Jerome/.well-known/openid-configuration
  client_id: 
  - 
  client_secret: 
  - 
  consumer_optional: true
  auth_methods: 
  - client_credentials
  verify_parameters: false
plugin: openid-connect