apiVersion: v1
kind: Service
metadata:
  name: httpbin
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: NodePort
  ports:
  - name: httpbin
    targetPort: 8080
    port: 8080
    protocol: TCP
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
      annotations:
        kuma.io/demo-backend: example-backends
    spec:
      containers:
        - name: httpbin
          image: svenwal/httpbin
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "1"